name: CI

on:
  push:
    branches: [ lab1 ]
  pull_request:
    branches: [ lab1 ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./lab1type  
    
    steps:
    - uses: actions/checkout@v3

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm test

    - name: Run coverage
      run: pnpm coverage
